#+TITLE: Expect Franco
#+AUTHOR: saadnpq
#+DATE: 2019:5:20
#+OPTIONS: \n:t num:t toc:t
#+SETUPFILE: ./theme-readtheorg.setup
  
* state of the project
the project is still in early development, but it's usable and reaching a more stable state with time, major changes happen less often and basic cases has been coverd.
to follow or to contribute to the project maintenance see the [[https://github.com/saadnpq/expect-franco][github repository]].
* abstract
the project is supposed to be an implementation of ideas introduced in [[https://saadnpq.com/posts/franco/][this blog post]], to understand the rationale behind all of this, or to have a better insight about the issue of the arabic writing system, please refer to blog post.
* why?
- to have a standardized, written, documented and community developed Franco flavor.
- to have a consistent and searchable Arabic writing system.
- a reference for people with unreadable Franco
* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, however, it should not conflict with it (English alphabet).
3) as much as we can, there should be only one "right" way to write a word to achieve searchability.

* Character transliterations
  
| traditional | Franco | unicode name                   |
|-------------+--------+--------------------------------|
| ا           | a      | ARABIC LETTER ALEF             |
| آ           | aa     | ARABIC LETTER WITH MADDA ABOVE |
| ء           | 2      | ARABIC LETTER HAMZA            |
| ب           | b      | ARABIC LETTER BEH              |
| ت           | t      | ARABIC LETTER TEH              |
| ث           | $      | ARABIC LETTER THEH             |
| ج           | g,j    | ARABIC LETTER JEEM             |
| ح           | 7      | ARABIC LETTER HAH              |
| خ           | 5      | ARABIC LETTER KHAH             |
| د           | d      | ARABIC LETTER DAL              |
| ذ           | >      | ARABIC LETTER THAL             |
| ر           | r      | ARABIC LETTER REH              |
| ز           | z      | ARABIC LETTER ZAIN             |
| س           | s      | ARABIC LETTER SEEN             |
| ش           | 4      | ARABIC LETTER SHEEN            |
| ص           | S      | ARABIC LETTER SAD              |
| ض           | D      | ARABIC LETTER DAD              |
| ط           | T      | ARABIC LETTER TAH              |
| ظ           | Z      | ARABIC LETTER ZAH              |
| ع           | 3      | ARABIC LETTER AIN              |
| غ           | 8      | ARABIC LETTER GHAIN            |
| ف           | f      | ARABIC LETTER FEH              |
| ق           | 9      | ARABIC LETTER QAF              |
| ك           | k      | ARABIC LETTER KAF              |
| ل           | l      | ARABIC LETTER LAM              |
| م           | m      | ARABIC LETTER MEEM             |
| ن           | n      | ARABIC LETTER NOON             |
| ه           | h      | ARABIC LETTER HEH              |
| و           | w      | ARABIC LETTER WAW              |
| ى           | y      | ARABIC LETTER YEH              |

** Capital letters

the fact that Capital letters doesn't have any phonetic differences than lower case letters, makes it a perfect candidate to be included in Franco, as it is "backward compatible", by backward compatible we mean that if someone for example wrote ط as T instead of t, it won't effect the interpretation of the word if the receiver doesn't know this mapping. we basically loose nothing -[[*what we loose][ kinda]] - but we gain more clarification and disambiguation.

*** capital consonants 
we choose the following letters to have a Capital letter transliteration due its phonetic similarities with letters transliterated to the corresponding lower case letters.

| traditional | Franco | unicode name      |
| ض           | D      | ARABIC LETTER DAD |
| ط           | T      | ARABIC LETTER TAH |
| ظ           | Z      | ARABIC LETTER ZAH |
| ص           | S      | ARABIC LETTER SAD |

*** what we loose
- capitalization of names in Franco text, which is not used already.
- some minor confusion may arise in one case that requires three conditions to occur:
  1) a capitalized English word that starts with one of the few mapped capital letters in Franco
  2) that capitalized name exits alone without English context and surrounded by Franco text.
  3) that word can be interpreted as a Franco word
  but since this case is very unlikely to occur and relying on context is inevitable in mixed text anyway. it's not reasonable to throw all the benefits for such a rare case.

** <<<Digraphs>>>
Digraphs are two letters that behaves as a unit and is not the sum of its parts, e.g. "ch", "sh", "kh" and "th" in English.
Digraphs are ugly and makes words longer and harder to read, specially for repeated letters, i.e. shadda.

| digraph     | Franco |
|-------------+--------|
| kh          |      5 |
| sh          |      4 |
| gh          |      8 |
| dh          |      D |
| th in throw |      $ |
| th in the   |      > |

* diacritics and vowels
the table below shows the basic diacritics transliterations.

| traditional | Franco | Unicode name |
| َ            | a      | ARABIC FATHA |
| ُ            | o      | ARABIC DAMMA |
| ِ            | e      | ARABIC KASRA |

** long vowels
| traditional | Franco | Unicode name                      |
| ُ +و         | O      | ARABIC DAMMA + ARABIC LETTER WAW  |
| ِ +ى         | E      | ARABIC KASRA + ARABIC LETTER YEH  |
| َ +ا         | A      | ARABIC FATHA + ARABIC LETTER ALEF |

*** importance of long vowels (A,E,O)
without those we have no distinction between lots of words, for example:
- zaman and zamAn
- men and mEn
- 7aram and 7arAm
- malak, malAk, mAlak
  
*** why not oo,aa,ee ?
they appear so often in arabic - sometimes many times in one word - and they tend to make words a lot longer. they are used only in the beginning of words like aah, eed, oom.
 
** additional diacritics not in the traditional system
for those we use diphthongs, i.e. compound vowels.
   | diacritic | examples                 | note            |
   |-----------+--------------------------+-----------------|
   | ei        | leih (why), beit, la2eit | "E" but lighter |
   | oa        | moat (death), Soat, noam | "O" but lighter |

*** why we need new diacritics
the traditional system has no way to resolve the difference between for example:
- mOt and moat
- kOn and koan
- rO7 and roa7
- TEr and Teir

* <<<shadda>>>
shadda in Arabic is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by.. yeah, you guessed it.. a repeated letter, e.g. yalla, ba7ebbek, kollo.
some people omit the second letter, causing one of the biggest sources of ambiguity in Franco text, as omitting the second letter normally yields a different word. try to convince your wife that the message "ha3ady 3aleik bel mara" she found on your phone is supposed to be "ha3addy 3aleik bel marra" to know how important this is. we can't emphasize more that the second letter is not optional and text compliant to this guideline should always write repeated letters whenever there is a shadda.

** COMMENT shadda with 8ein
some people write 8en as 3', if you can't loose this habit, don't omit the shadda because it's ugly to write "sha3'3'Al" for example; in this case you can write it "sha3"Al" where 3" = 3'3' = 3' + shadda, but this sounds over engineered. for reasons like this we recommend against 3', use 8. 
the previous concept applies also if you are used to use 7' instead of 5 - for god knows why.

* The hyphen "-"

hyphen has three use cases:
+ the hyphen in Franco is used when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the "sh" and "th" sequence. for example: sme3t /sot-ha/, byet-hayya2lak, as-hal, btet-haz
+ to separate english words from franco prepositions like: aa3ed /ba-chill/, 3reft a-configure el btA3.
+ hyphens can optionally be used after the definite article to ease readability, see [[*the definite article "el"][the definite article]].

* the definite article "el"
based on what dialect you are writing in, the definite article can be "el" or "al". just write what you pronounce.
"el" ( or "al") in Franco is never attached directly to the following word, it can be either written separately or attached with a hyphen, e.g. /el walad/ or /el-bent/. choose whatever you like, what matters is to be consistent.
some words start with letters (sun letters) that assimilate the "l" in the definite article so that l is removed and shadda is added to the letter. for example some words like /el naharda/ are often pronounced as /en-naharda/, whether or not this increases readability or not is very dependent on the context and the word itself, if you choose to assimilate the "l" in some word you should write it like /en-naharda/, not /en naharda/ or /ennaharda/.

* prepositions
| traditional | Franco | example             |
|-------------+--------+---------------------|
| ب           | b      | b we4 reglak        |
| و           | w      | a7la w a7la         |
| -ل          | l      | a4ky l mEn          |
| في          | f/fe   | kont f bAly         |
| على         | 3la    | 3la mAgy            |
| ف           | fa     | fa yakOn            |
| اللى        | elly   | elly hnAk da        |
| ما          | ma     | 3omrena ma hanerga3 |
| من          | men    | em4y men hena       |
| من ال       | mel    | mel ko4k            |
| من اللى     | melly  | melly hnAk da       |
| على ال      | 3al    | 3al mA4y            |
| إلي ال      | lel    | ray7a lel banAt     |
| في ال       | fel    | fel konAfa          |
| ب ال        | bel    | bel habal           |

prepositions inherit the same rules of attaching from the definite article, by that we mean that for example "fel konaafa" can be written as "fel-konaafa", and if you want to assimilate the l of the definite article in this word it should be written as "fek-konaafa".
ma can optionaly be attached directly to the following word. e.g. 3omry mansa.

** post-positions
  | traditional | Franco | example       |
  |-------------+--------+---------------|
  | دي          | de     | el bta3a de   |
  | ده          | da     | el bta3 da    |
  | دول         | doal   | el btoo3 doal |
  
* Don't start with "2"
since vowels 

| example | should be |
|---------+-----------|
| 2na     | ana       |
| 2amar   | amar      |
| 2egry   | egry      |
| 2oddAm  | oddAm     |
| 2e2lAm  | e2lAm     |
| 2Ol     | ool       |

* general notes
** Arabic names
Arabic names should not be written in Franco, because simply no one has the right to decide how a name is pronounced other than the name holder himself.

** e in the end is y
  seeby not seebe
  
** the ghost vowel
this is an Egyptian dialect thing, we tend to not pronounce the second letter if it's a vowel.

- btA3 not betA3 
- ktEr not ketEr
- hnAk not henAk 
- m3Ak not ma3Ak 

but sometimes it's pronounced very clearly in certain words, we don't know if there is a well defined grammatical pattern that governs this phenomena, but we can say that if you don't know which way to go, remove the vowel.

* sample text
it's known that the beauty of a language comes from the beauty of text it has been written in. below are different pieces of text written in compliant franco, that we think are beautiful.
poems from "dorg el 9Ahera" by the beautiful mostafa ibrahem:
-------
9awA3ed el dayra el saba3a (5):

ezzay te3raf..
mEn sAbe2 mEn gowwa el dayra..
w mEn feha aTa3 aTwal me4wAr..
m4 momken bardo elly fDahrak..
yeTla3 sab2ak..
w enta elly 7mAr ?!
-------
9awA3ed el dayra el saba3a (3):

far2 el sor3At gowwa el dayra
beink w mabein kol el ma4yEn
howwa elly haye2dar yeDmanlak
en enta t2Abel nAs tanyEn
-------
9awA3ed el dayra el saba3a (1):

ab3ad no2Ta bel nesbAlak
gowwa el dayra.. heyya makAnak
w ka2enn asAsn fel dayra
hena.. howwa hnAk
fa TabE3y t7es enk 3Aye4..
b etnein gowwak
------
akEd el 4am3a lw kAnt.. 
la2et forSa..
w 7al morE7..
y3ayye4ha.. bdOn matsE7..
w ye7faZ 4aklaha el sAbet..
kant 3A4t !!
-------------
aalet el donya lel walad f el faSl
yat3E4 btektb warAya..
fel 7eSSa, yat3e4ha 
ensa en feh fel faSl sabbOra 

aal el moSawwer lelly gAb camera
yat3E4 btA5od Sowar..
lel 9essa, yat3e4ha
el kadr dayman a8la mel SOra

ya donya ana bakteb..
lel gay ba3deyya..
wana gay ba3dy olOf
w en kont bA5od Sowar..
lel 9essa m4 leyya
fana nefsy 8eiry y4Of
-------
bdOn ma3raf sabab wADe7..
34An az3al.. ana za3lAn
w fag2a bdOn sabab bardo..
yfarra7ny.. bakOn far7An
la menny 3reft a3ml eih..
34An maz3l4 mn tAny..
wala menny..
3reft ezzay..
adO2 el far7a bel maggan
-------
ba3d ma aDDa noS el modda..
fata7o bAb zenzanto el SAg..
a5ado menno kol el 3ohda..
4Alo malaffo men el edrAg
3am m7ammad mAt mel we7da..
awel yoam ba3d el efrAg
------
for more sample text that covers many more cases, please refer to the sample directory in the git repository [[https://github.com/saadnpq/expect-franco/tree/master/sample][here]].
* TODO FAQs
** what is the problem with the traditional system?
[[https://saadnpq.com/posts/franco/][this]] blog post may answer this question.
** why this guideline written in English and not in Franco?
   this is an evolving guideline. if it is written in Franco, every update in the guideline means rewriting every thing to be compliant with itself.
** are you working on Franco to replace the traditional Arabic system?
Franco is just an alternative writing system that can coexist with any other writing system. we think Franco has more potential than Arabic in many situations like writing modern Arabic dialects and mixed English-Arabic text, but Franco is not yet capable of writing pure traditional Arabic text like Quran for example. when this guideline reaches a solid state we can test it against old Formal texts and see what are the limitations.

* TODO how to learn the system
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# after-save-hook: org-html-export-to-html
# End:
