#+TITLE: Franco guideline draft
#+AUTHOR: saadnpq
#+DATE: 2019:5:20

* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, though it should not conflict with English alphabet.
3) this guideline concern itself with readability and beauty as well.

* Character transliterations
  
| traditional | Franco | unicode name        |
|-------------+--------+---------------------|
| ا           | a      | ARABIC LETTER ALEF  |
| ء           | 2      | ARABIC LETTER HAMZA |
| ب           | b      | ARABIC LETTER BEH   |
| ت           | t      | ARABIC LETTER TEH   |
| ث           | th     | ARABIC LETTER THEH  |
| ج           | g,j    | ARABIC LETTER JEEM  |
| ح           | 7      | ARABIC LETTER HAH   |
| خ           | 5      | ARABIC LETTER KHAH  |
| د           | d      | ARABIC LETTER DAL   |
| ذ           | th     | ARABIC LETTER THAL  |
| ر           | r      | ARABIC LETTER REH   |
| ز           | z      | ARABIC LETTER ZAIN  |
| س           | s      | ARABIC LETTER SEEN  |
| ش           | 4      | ARABIC LETTER SHEEN |
| ص           | S      | ARABIC LETTER SAD   |
| ض           | d,D    | ARABIC LETTER DAD   |
| ط           | t,T    | ARABIC LETTER TAH   |
| ظ           | z,Z    | ARABIC LETTER ZAH   |
| ع           | 3      | ARABIC LETTER AIN   |
| غ           | 3'    | ARABIC LETTER GHAIN |
| ف           | f      | ARABIC LETTER FEH   |
| ق           | q      | ARABIC LETTER QAF   |
| ك           | k      | ARABIC LETTER KAF   |
| ل           | l      | ARABIC LETTER LAM   |
| م           | m      | ARABIC LETTER MEEM  |
| ن           | n      | ARABIC LETTER NOON  |
| ه           | h      | ARABIC LETTER HEH   |
| و           | w      | ARABIC LETTER WAW   |
| ى           | y      | ARABIC LETTER YEH   |

* diacritics transliterations
| traditional | Franco | unicode name                                |
| َ            | a      | ARABIC FATHA                                |
| ُ            | u/o    | ARABIC DAMMA                                |
| ِ            | i/e    | ARABIC KASRA                                |
| ُ +و         | oo/ou  | ARABIC DAMMA followed by ARABIC LETTER WAW  |
| ِ +ى         | ee     | ARABIC KASRA followed by ARABIC LETTER YEH  |
| َ +ا         | aa     | ARABIC KASRA followed by ARABIC LETTER ALEF |

** additional diacritics not in the traditional system
for those we use diphthongs (compound vowels).
   | diacritic | examples                                      | note                           |
   |-----------+-----------------------------------------------+--------------------------------|
   | oa        | moat (death), soat (sound), noam (sleepiness) | "oo" but lighter (closer to a) |
   | ea        | leah (why),                                   | "ee" but lighter (closer to a) |

*** should we stick to diphthongs as in English or we should make another sounds 
# should we go with ea or ei

* <<<shadda>>>
shadda in Arabic is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by.. yeah, you guessed it.. a repeated letter, e.g. yalla, ba7ebbek, kollo.

some people omit the second letter, causing one of the biggest sources of ambiguity in Franco text, as omitting the second letter normally yields a different word. try to convince your wife that the message "ha3dy 3alek bel mara" she found on your phone is supposed to be "ha3ddy 3alek bel marra" to know how important this is. we can't emphasize more that the second letter is not optional and text compliant to this guideline should always write words that pronounced with shadda with two letters.

** shadda with 3'
there is a special case only for 3' where it's ugly to write for example sha3'3'al(working). in this case we write it as sha3"al. so 3" = 3'3' = 3' + shadda.

* <<<Digraphs>>> avoidance
Digraphs are two letters that behaves as a unit and is not the sum of its parts, e.g. "ch", "sh", "kh" and "th" in English.

Digraphs are ugly and makes words longer and harder to read, specially for repeating letters, i.e. shadda.
the only Digraph we use is "th". we are going with it now because it's rarely used in the Egyptian dialect and seems to be no sane alternative right now, this may be changed in further versions if some one contributed a good idea.

*** TODO 5 instead of kh
    
*** 4 instead of sh
why 4 to represent sh and not x for example like Maltese (which is so close to be an Arabic dialect written with Latin letters) and many Latin languages?

- 4 is already present in some new flavors of Franco.
- it is easier also to figure out its meaning if you didn't see it before. (easier than x which requires unlearning first then learning).
- adheres more to the basic idea that distinguishes Franco from any other system, assigning sound to numbers.

* The hyphen
the hyphen in Franco is used when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the "sh" and "th" sequence. for example:
- ana /s-hert/ embare7 l7ad elsa3a 3
- ana ennhrda s7et 3la /sot-ha/
 
hyphens can optionally be used after the definite article to ease readability.

* the definite article "el"
based on what dialect you are writing in, the definite article can be "el" or "al". just write what you pronounce.

"el" ( or "al") in Franco is attached to the following word either directly or with a hyphen, e.g. /elwalad/ or /el-bent/.

some words starts with letters (sun letters) that assimilate the "l" in the definite article so that l is removed and shadda is added to the letter. for example some words like /elnahrda/ are often pronounced as /ennahrda/. both are valid ways to write the word. but note that if you are hyphening the word /ennahrda/, it's hyphened like /en-nahrda/.

to wrap up, you can write /elkonafa/ without hyphens either as /elkonafa/ or /ekkonafa/ or /ek-konafa/, /el-konafa/,

* prepositions
| traditional | Franco | attached | example       |           |
|-------------+--------+----------+---------------+-----------|
| في          | fe     | yes      | fekkonafa     | felkonafa |
| ب           | be     | yes      | berra7a       | belra7a   |
| على         | 3la    | depends  | sho5 3alwel3a |           |
| ف           | fa     | yes      | faro7t        |           |

prepositions like /be/ (“with”) or /fe/ (“in”) should be attached to the following definite article, thus becoming one entity bel or fel. and both should be attached the following word like bel-konafa

* Don't start with "2"
it's useless and ugly. 

| example     | should be  |
|-------------+------------|
| 2na         | ana        |
| 2amal maher | amal maher |
| 2egry       | egry       |
| 2e2lam      | e2lam      |
| 2oddam      | oddam      |

* TODO sample text
  here we should put a sample text that covers all possible cases.
