#+TITLE: Compliant Franco
#+AUTHOR: saadnpq
#+DATE: 2019:5:20
#+OPTIONS: \n:t num:t toc:t timestamp:nil
#+SETUPFILE: ./theme-readtheorg.setup
  
* state of the project
the project is still in early development, but it's usable and reaching a more stable state with time, major changes happen less often and basic cases has been covered.
to follow or to contribute to the project maintenance see the [[https://github.com/saadnpq/expect-franco][github repository]].
* abstraction
this project is supposed to be an implementation of ideas introduced by [[https://saadnpq.com/franco/embrace-franco.pdf][this research article]]. to understand the rationale behind all of this, or to have a better insight about the issue of the Arabic writing system, please refer to the article.
* why?
- to have a standardized, documented, eloquent, and community developed Franco flavor.
- to have a consistent, searchable and bidirectional friendly Arabic writing system.
- a reference for people with unreadable Franco
* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, however, it should not conflict with it (English alphabet).
3) as much as we can, there should be only *one* "right" way to write most word.

* abbreviations and acronyms used throughout the document
- <<<TAWS>>> :: the Traditional Arabic Writing System
- <<<CvC>>> :: consonant + short vowel + consonant

* consonants
this is not a transliteration system, but for your convenience we compare the symbols of Franco to those of TAWS which we are used to - instead of IPA for example. is you want a map of consonants in franco that is independent from TAWS, maybe for non-arabic speakers, see [[*independent map of consonants][independent map of consonants]].

| TAWS | Franco |
|------+--------|
| ا    | a      |
| آ    | aa     |
| ء    | 2      |
| ب    | b      |
| ت    | t      |
| ث    | $      |
| ج    | g,j    |
| ح    | 7      |
| خ    | 5      |
| د    | d      |
| ذ    | 6      |
| ر    | r      |
| ز    | z      |
| س    | s      |
| ش    | 4      |
| ص    | S      |
| ض    | D      |
| ط    | T      |
| ظ    | Z      |
| ع    | 3      |
| غ    | 8      |
| ف    | f      |
| ق    | 9      |
| ك    | k      |
| ل    | l      |
| م    | m      |
| ن    | n      |
| ه    | h      |
| و    | w      |
| ى    | y      |

** <<<Digraphs>>>
Digraphs are two letters that behaves as a unit and is not the sum of its parts, e.g. "ch", "sh", "kh" and "th" in English.
Digraphs are basically an ugly hack to the English writing system, when used with other languages which uses them a lot, as in our case, it makes words longer and harder to read, specially for repeated letters, i.e. shadda.

| English     | Franco |
|-------------+--------|
| kh          |      5 |
| sh          |      4 |
| gh          |      8 |
| dh          |      D |
| th in throw |      $ |
| th in the   |      6 |

** don't start with "2"
since in most Latin languages e,o,a in the beginning of words contain the "2" in their pronounciation, we can borrow this property.

| example | should be |
|---------+-----------|
| 2na     | ana       |
| 2aMaR   | aMaR      |
| 2egry   | egry      |
| 2oddAm  | oddAm     |
| 2e2lAm  | e2lAm     |
| 2Ol     | ool       |

* Capital letters
the fact that Capital letters doesn't have any phonetic differences than lower case letters, makes it a perfect candidate to be included in compliant Franco.

** Velarization -> capital consonants 
many consonants in many languages can be *velarized*, velarization is a property that gives a duller sound to the consonant which also affects the neighboring vowels.

from wikipedia
#+begin_quote
Velarization is a secondary articulation of consonants by which the back of the tongue is raised toward the velum during the articulation of the consonant.
#+end_quote

in TAWS "ض ط ظ ص" are examples of veralized consonants that have a character representation, but in reality other consonants such as "l,r,b,m" can also be velarized. those consonants are assigned capital letters in compliant Franco.

| TAWS | Franco | example with |
| ض    | D      | 3aDalAT      |
| ط    | T      | TAr          |
| ظ    | Z      | ZeiTa        |
| ص    | S      | SAber        |
| -    | B      | BAba         |
| -    | M      | MAyya        |
| -    | R      | RAye7        |
| -    | L      | aLLAh        |

we choose those consonants since they are "backward compatible", by backward compatible we mean if someone for example wrote ط as T instead of t, it won't effect the interpretation of the word if the receiver doesn't know this mapping. we basically lose nothing -[[*what we loose][ kinda]] - but we gain more clarification and disambiguation.

we use also capital letters to represent long vowels, see [[*diacritics and vowels][diacritics and vowels]].

*** importance of capital consonants
without those we have no distinction between many words, for example:

- fos7a and foS7a
- bass and baSS
- 7aZZ and 7azz
- gARy(my neighbor) and gAry (current)
- garrA7 and gaRRA7
- etrabbeit and etRaBBeit
- SAB and sAb
- mafROD and mafrOd
- enSef and ensef
- Dall and dall
- DAr  and dAr
- Ba3D and ba3d
- TAR and tAr
- BAT and bAt
- DahR and dahr
 
** what we lose
we obviously lose capitalization of names in Franco text, which is not used already.

* diacritics and vowels
** short vowels
the table below shows the basic diacritics transliterations.

| traditional | Franco | Unicode name |
| َ            | a      | FATHA        |
| ُ            | o      | DAMMA        |
| ِ            | e      | KASRA        |

** long vowels
| traditional | Franco | Unicode name  |
| ا + َ        | A      | FATHA +  ALEF |
| و + ُ        | O      | DAMMA +  WAW  |
| ى + ِ        | E      | KASRA +  YEH  |

*** importance of long vowels (A,E,O)
without those we have no distinction between lots of words, for example:
- zaman and zamAn
- men and mEn
- 7aRaM and 7aRAM
- malak, malAk, mAlak
  
*** why not oo,aa,ee ?
they appear so often in arabic - sometimes many times in one word - and they tend to make words a lot longer. they are used only in the beginning of words like aah, eed, oom.
 
** additional diacritics not in TAWS
for those we use diphthongs, i.e. compound vowels.
   | diacritic | examples           | note            |
   |-----------+--------------------+-----------------|
   | ei        | leih (why), la2eit | "E" but lighter |
   | oa        | moat (death), noam | "O" but lighter |
   
*** why we need new diacritics
the traditional system has no way to resolve the difference between for example:
- mOt and moat
- kOn and koan
- rO7 and roa7
- TER and TeiR
- betO3 and betoa3
- dEn and dein
- fO2 and foa2

*** more examples
for didactic purposes someone may want more examples.
**** ei
- yareit
- bein el-benein
- eih
- leila
- 8eir
- 4ei2
- fein
- etnein, metein, toffa7tein, etc.
- la2eit, 7abbeit, geit, etc.
- 3eneik, regleik, edeik, etc.
- 3eneiha, regleiha, edeiha, etc.
 
**** oa 
- 4oak
- 4oa2
- doal
- loala
- Soam
- loan 
     
* <<<shadda>>>
shadda in TAWS is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by - yeah, you guessed it - a repeated letter, e.g. yaLLa, ba7ebbek, kollo.

people with poor Franco often omit the second letter causing one of the biggest sources of ambiguity in mainstream Franco text, as omitting the second letter normally yields a different word. try to convince your wife that the message "hagElak bel-MaRa" she found on your phone is supposed to be "hagElak bel-MaRRa" to know how important this is. we can't emphasize more that the second letter is not optional and text compliant to this spec should always write the shadda appropriately wherever it appears.

examples:
- 4adda
- howwa
- heyya
- lessa
- 5omsomeyya
- 9essa
- mosta3edda

* The hyphen
the hyphen, i.e. "-", has three use cases:
+ after the definite article
+ after "ma", e.g. "ma-balA4"
+ when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the "sh" and "th" sequence. for example: sme3t /sot-ha/, byet-hayya2lak, as-hal, btet-haz
+ to fit English words in Arabic grammer like: aa3ed /ba-chill/, 3reft a-configure el-btA3.

* <<<the definite article>>>
the definite article in compliant Franco is not as simple as "the" in English or "-ال" in TAWS. generally it can appear as "el-...", "l-...", "eX-X..." or "X-X..."(where X represents on of the sun letters discussed [[*sun letters][here]]).

for programmers, this Emacs-style regular expression will match all possible forms a definite article can take in compliant Franco: 
#+begin_example
e?\(?:l\|\([tT$6dDrzZnsS4kg]\)\)-\1?
#+end_example

** sun letters
some words start with letters called sun letters (shown below) that has the effect of turning the "l" to a copy of itself, i.e. shadda. for example /el naharda/ should be written as /en-naharda/ like how it's actually pronounced 

| letter | example                |
|--------+------------------------|
| t      | et-tegAh wA7ed         |
| T      | SoLTAn eT-TaRaB        |
| $      | e$-$a9Afa el-3aRaBeyya |
| >      | wa9t e6-6orwa          |
| d      | omm ed-donya           |
| D      | el-wa2t eD-DAye3       |
| r      | ya de7ket eR-RoMMan    |
| z      | ez-zaman TawEl         |
| Z      | eZ-ZAheR keda          |
| n      | eR-Rakk 3an-neyya      |
| s      | zayy es-sokkaR        |
| S      | eS-So7AB fe'agAza      |
| 4      | 3ala add e4-4oa2       |
| k      | fek-konAfa             |
| g      | eg-gei4 we4-4orTa      |

note that the Egyptian dialect/language has two more sun letters than arabic, the "k" and "g".

** moon letters
moon letters are straight forward, they are not sun letters and they don't touch the "el".
examples:
- el-lo8a 
- el-3ammeyya
- el-MaSReyya
- el-9Ahera
- el-ward
- el-balady
- w keda

** to "e" or not to "e"
that is the question. the rule is similar to what's described later in [[*shortening (Egyptian specific)][shortening]]. it depends on the preceding word, if it ends with "a" or "o", the e is ommited. for example:

- ana l-awwal wana l-aa5er
- 3ala l-mA4y
- lessa d-donya b'5eir
- eih yabo r-reggAla
- mesa g-gamAl

* prepositions
prepositions in compliant franco are attached to following word using apostrophe (') or a backtick (`)

| TAWS   | Franco | example             |
|--------+--------+---------------------|
| ب      | b/be   | b'we44 reglak       |
| و      | w/we   | a7la w'a7la         |
| -ل     | l/le   | a4ky l'mEn          |
| في     | f/fe   | kalAm fe'kalAm      |
| على    | 3ala   | 3ala'mAgy           |
| من     | men    | 5o44 men'hena       |
| ف      | fa     | konn fa'yakOn       |
| اللى   | elly   | elly hnAk da        |
| ما     | ma     | 3omrena ma'hanerga3 |

for cases where the e is removed from be/we/le/fe, see [[*shortening (Egyptian specific)][shortening]].

** prepositions compound with definite article.

| traditional | Franco | example                   |
|-------------+--------+---------------------------|
| من ال       | mel    | mek-ko4k                  |
| ما ال       | mal    | tamAm TOl mal-balad tamAm |
| عال         | 3al    | 3al-mA4y                  |
| وال         | wel    | bel-yoam wel-yoamein      |
| لل          | lel    | Ray7a lel-banAt           |
| في ال       | fel    | fek-konAfa                |
| ب ال        | bel    | bel-habal                 |

those prepositions inherit the same rules of the definite article, by that we mean for example "fel-konAfa" should be written "fek-konAfa".

** demonstrative pronouns
  | traditional | Franco | example       |
  |-------------+--------+---------------|
  | دي          | de     | el-betA3a de  |
  | ده          | da     | el-betA3 da   |
  | دول         | doal   | el-betO3 doal |
  
* shortening (Egyptian specific)
in the Egyptian dialect/language, we tend to not pronounce the first occurrence of short vowel in some words, for example sometimes we say "kfAya" and sometimes we say "kefAya", in this section we will discuss this phenomena. all the conditions in this section also applies to prepositions be/we/le/fe.
** conditions for shortening
whether shortening will take place or not is governed by the ending of the preceding word, that is, if the ending of the preceding word is one of the following three cases, the vowel is deleted,
*** ends with a vowel(e,o,a), w or y.
 the most occuring case is if the preceding word ends with a vowel, for example we say "kefAya keda" and we say also "keda kfAya".

 examples :
 - ana ktEr 
 - ta3Ala hnAk
 - ya 5SARa
 - ana ndemt
 - mahma kbert
 - alby m3Ak
 - ta3Alo nnam
 
*** ends with two consecutive consonants
another case where the vowel is deleted, is when the preceding word ends with two consecutive consonants like "4oft", "", "esta7melt".. etc, for example:
 - 4oft ktEr
 - ro7t l3ebt
 - 4a3r TwEl
 - 4e3r kwayyes
 - la7m r5eS
 - 3e4t snEn
 - 7elm kbEr

 you may have noticed that this case is reducible to the first case, since we can't pronounce more than two consecutive consonants (the two from the end of the word and the first of the following) we add a very short vowel - called epenthetic vowel - at the end of the first word to make it pronounceable, so it becomes "4ofte ktEr" which is exactly the first case.

 this topic is actually more complicated than that, but most of the time it's clear for the Egyptian speaker which way to go, don't think about it too much.
 
 please note that in searching franco text we should take into consideration both writings, for example this [[https://duckduckgo.com/?q=what+is+regex&ia=web][regex]] "ke?tEr" will match every instance of the word regardless of whether shortening happened or not.

** COMMENT what are the candidate words for elision
for example why gAmed always gAmed regardless of the cases above, and regl as well.

* ending shadda ("maybe" Egyptian specific)
in compliant Franco some words must end with shadda for reasons discussed [[*rationale behind the shadda at the end][here]], this shadda appears in three cases (or two actually).
** CvC
for words that has the shape of (consonant + short vowel + consonant) like "7or" for instance, the last consonant is written as if there a shadda at the end, "7orr".

examples : 
- 7orr
- 7add
- hezz
- bass
- zayy
- koll
- morr
- sett
- foll
- ToLL
- 3akk
- fann
- lakk
- 3amm

the middle vowel must be a short one, for example "kAn" can't be written "kAnn" by any stretch of imagination.

** something + stop + CvC
some words doesn't have the shape of CvC, but ends with it after a brief stop, for example "haylef", those words are pronounced like "hay..lef" where the dots represent a brief stop. this is practically equivalent to pronouncing it as two separate words. here also the shadda is added by the same means we added it to "leff".

examples:
- a7ebb
- ye7ebb
- ma3le44
- ka2enn, akenn
- aMaRR 
- momell
- betmorr

note that the stop before the cvc is mandatory for the shadda to appear, for example "la2et" ends with CvC but the stop isn't there and so the shadda. 

** (a,o,e) + consonant
if you remember from the [[*don't start with "2"][don't start with "2"]] section, words that start with "a","o" or "e", when pronounced they begin with a hidden "2", so "omm" in reality has the shape of CvC, that is, the first consonant is the hidden "2", the second vowel is "o" and the third consonant is "m", which is exactly the first case.

examples:
- omm
- aBB
- a55
- add (add ed-donya)
- oTT
- ayy
- all (el-waga3 all 4wayya)

** rationale behind the shadda at the end
you may ask the following: what's the problem with writing it without the shadda like "7or" or "bas" since there is no ambiguity the shadda resolves and by definition there can't shadda that consists of two consonants (the second one must have vowel after it). for two reasons 

1) the reality is that most people now write unreadable Franco, and most people are used to read unreadable Franco, this caused a problem we call short/long vowel blindness. for example a word like "sab" will be interpreted by most people as "sAb", but "sabb" will be easier for the to read
2) the shadda actually exists if there is a following word, for example "sabb dEn". when you pronounce it you will notice a very short "e" after "sabb", it will sound something like "sabbe dEn".
3)consider this sentence - without the shadda at the end - "haylef ylef w'yerga3ly", if you pronounced it in Egyptian Arabic, you will observe two things:
   1) you shorten "yelef" so that it becomes "ylef" and you shorten "we" becoming "w"
   2) you pronounce a shadda in both "haylef" and "ylef"
but by the rules of shortening the shortening in "yelef" and "we" shouldn't be there, since the preceding words "haylef" and "ylef" respectively doesn't end by a vowel nor a two consonants, but if we wrote explicitly the shadda observed by pronunciation, the second rule of shortening apply (the preceding word ends with two consonants), which explains why the shortening happens. so writing the sentence like this "hayleff yleff w'yerga3ly" just solves every thing.

* Assimilation
Assimilation here is a term for sound changes that occur within a word to ease pronunciation, for example "ganby" becomes "gamby".
not all writing system reflect assimilation in its orthography, but since this writing system relies heavily on phonetics, and wants to be predictable and consistent, we choose to reflect it, so the "right" way to write, e.g. "zanby" is "zamby", "anbOba" is "ambOba"

* general notes
** Arabic names
Arabic names should not be written in Franco, simply because no one has the right to decide how a name is pronounced other than the name holder himself, but it's ok to write a name in franco if you don't know how it's pronounced.

for example:
- yousef not yOsef
- mohammed mounir not ma7ammad monEr.

** e or y in the end
in Egyptian Arabic, y and e in the end have no difference and can be used interchangeably, for consistency we will use y in the end, e.g. "sEby" not "sEbe".

** no place for those
compliant Franco does not contain any of the following english characters: [q,c,x,u,p,v], except in English words or human names.
similarly the following sequences of characters doesn't appear in compliant Franco: [sh,kh,th,gh], instead, those characters appear hyphenated to prevent confusion, e.g. s-h,k-h,t-h. see [[*The hyphen][The hyphen]].
** additional shortening cases
in "we" the e is deleted when the following word is starts with "a,o,e" - in addition to the normal conditions of shortening. for example in "a4ky l'mEn w'a7ky l'mEn" the "we" is shortened despite the normal conditions of shortening does not hold here, but it's because a7ky starts with "a"
examples:
- harO7 w'aagy b'soR3a
- 2Ol w'egry
- 2Ol w'oom
* sample text
it's known that the beauty of a language comes from the beauty of text it has been written in. below are different pieces of text written in compliant Franco, that we think are beautiful.

for more sample text that covers many more cases, please refer to the sample directory in the git repository [[https://github.com/saadnpq/expect-franco/tree/master/sample][here]].

in the beginning was the word, "ek-kelma dein" by ahmed foad negm.
-------
morr ek-kalAm.. zayy el-7oSam
ye2Ta3 makAn.. maymorr
amma el-madE7.. sahl w'morE7
ye5da3 Sa7E7.. w'y8orr
wek-kelma dein.. men'8eir edein
bass el-wafa.. 3al-7orr
-------

** poems by the beautiful mostafa ibrahem:
-------
9awA3ed ed-dayra es-saba3a (5):

ezzay te3raf..
mEn sAbe2 mEn gowwa ed-dayra..
w'mEn feha aTa3 aTwaL me4wAR..
me4 momken BaRDo elly f'DahRak..
yeTLa3 sab2ak..
w'enta elly 7MAR ?!
-------
9awA3ed ed-dayra es-saba3a (3):

far2 es-soR3At gowwa ed-dayra
beink we'mabein koll el-ma4yEn
howwa elly haye2dar yeDmanlak
en enta t2Abel nAs tanyEn
-------
9awA3ed ed-dayra es-saba3a (1):

ab3ad no2Ta ben-nesbAlak
gowwa ed-dayra.. heyya makAnak
we'ka2enn asAsn fed-dayra
hena.. howwa hnAk
fa'TabE3y t7ess ennak 3Aye4..
b'etnein gowwak
------
akEd e4-4am3a law kAnet.. 
la2et foRSa..
we'7all morE7..
ye3ayye4ha.. bedOn matsE7..
w'ye7faZ 4aklaha es-sAbet..
kanet 3A4t !!
-------------

* COMMENT corner cases and current limitations (Egyptian specific)
** can be written in .. or ..
due to the structure of the Egyptian dialect/language (and human languages in general) some sentences can be written in multiple ways and the writing system can't force one way or the other.

examples:
- "gondy f'gonOdek" or "gondy fe'gnOdek"
- "3ayez anAm" or "3ayz anAm" or 3Ayez anAm" or "3Awez anAm"

** special cases in shadda in the end of a word
- "lak" in "ana lak 3ala TOl", "lakk" is another word.
- "men" in "men'hena"

* FAQs
** what is the problem with the traditional system?
[[https://saadnpq.com/posts/franco/][this]] article may answer this question, and more.
** why this guideline written in English and not in Franco?
i agree this would be a cool idea, but this is an evolving guideline, if it is written in Franco, every update in the specification means rewriting every thing to be compliant with itself.
** are you working on Franco to replace TAWS?
Franco is just an alternative writing system that can coexist with any other writing system. we think Franco is very capable and has more potential than TAWS in many situations, like writing modern Arabic dialects and bidirectional text(mixed Arabic and English), but compliant Franco is not yet near ready for replacing TAWS in writings such as the Quran for example. for now we just focus on making a superior system, and maybe we can ask this question again later.

* miscellaneous
** independent map of consonants  
   
| manner        | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|---------------+---+---+---+---+---+---+---+---|
| Plosives:     |   |   |   |   |   |   |   |   |
| -> unvoiced   |   |   | t |   | k | 9 |   | 2 |
| ->> emphatic  |   |   | T |   |   |   |   |   |
| -> voiced     | b |   | d |   | g |   |   |   |
| ->>  emphatic | B |   | D |   |   |   |   |   |
|               |   |   |   |   |   |   |   |   |
| Fricatives:   |   |   |   |   |   |   |   |   |
| -> unvoiced   |   | f | s | 4 | 5 |   | 7 | h |
| ->> emphatic  |   |   | S |   |   |   |   |   |
| -> voiced     |   | v | z | j | 8 |   | 3 |   |
| ->> emphatic  |   |   | Z |   |   |   |   |   |
|               |   |   |   |   |   |   |   |   |
| the R-sound   |   |   | r |   |   |   |   |   |
| ->> emphatic  |   |   | R |   |   |   |   |   |
|               |   |   |   |   |   |   |   |   |
| the L-sound   |   |   | l |   |   |   |   |   |
| ->> emphatic  |   |   | L |   |   |   |   |   |
|               |   |   |   |   |   |   |   |   |
| Nasals        | m |   | n |   |   |   |   |   |
| ->> emphatic  | M |   |   |   |   |   |   |   |
|               |   |   |   |   |   |   |   |   |
| Semi-vowels   | w |   |   | y |   |   |   |   |

where the numbered columns represent the place of articulation:
- 1= with both lips
- 2= with the lower lip against the upper teeth
- 3= with the tip of the tongue against the back of the teeth
- 4= with the back of the tongue against the hard palate
- 5= with the back of the tongue against the soft palate
- 6= with the back of the tongue against the uvula
- 7= in the pharynx
- 8= in the glottis (glottal)

acknowledgment: this table is taken from "kullu tamam by manfred woidich".

* TODO how to learn the system
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# after-save-hook: org-html-export-to-html
# End:
