#+TITLE: Franco guideline draft
#+AUTHOR: saadnpq
#+DATE: 2019:5:20

* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, however, it should not conflict with English alphabet.
3) this guideline concern itself not only with readability, but with beauty as well.

* Character transliterations
  
| traditional | Franco | unicode name        |
|-------------+--------+---------------------|
| ا           | a      | ARABIC LETTER ALEF  |
| ء           | 2      | ARABIC LETTER HAMZA |
| ب           | b      | ARABIC LETTER BEH   |
| ت           | t      | ARABIC LETTER TEH   |
| ث           | th     | ARABIC LETTER THEH  |
| ج           | g,j    | ARABIC LETTER JEEM  |
| ح           | 7      | ARABIC LETTER HAH   |
| خ           | 5      | ARABIC LETTER KHAH  |
| د           | d      | ARABIC LETTER DAL   |
| ذ           | th     | ARABIC LETTER THAL  |
| ر           | r      | ARABIC LETTER REH   |
| ز           | z      | ARABIC LETTER ZAIN  |
| س           | s      | ARABIC LETTER SEEN  |
| ش           | 4      | ARABIC LETTER SHEEN |
| ص           | S      | ARABIC LETTER SAD   |
| ض           | d,D    | ARABIC LETTER DAD   |
| ط           | t,T    | ARABIC LETTER TAH   |
| ظ           | z,Z    | ARABIC LETTER ZAH   |
| ع           | 3      | ARABIC LETTER AIN   |
| غ           | 8     | ARABIC LETTER GHAIN |
| ف           | f      | ARABIC LETTER FEH   |
| ق           | q      | ARABIC LETTER QAF   |
| ك           | k      | ARABIC LETTER KAF   |
| ل           | l      | ARABIC LETTER LAM   |
| م           | m      | ARABIC LETTER MEEM  |
| ن           | n      | ARABIC LETTER NOON  |
| ه           | h      | ARABIC LETTER HEH   |
| و           | w      | ARABIC LETTER WAW   |
| ى           | y      | ARABIC LETTER YEH   |

* diacritics transliterations
| traditional | Franco | unicode name                                |
| َ            | a      | ARABIC FATHA                                |
| ُ            | u/o    | ARABIC DAMMA                                |
| ِ            | i/e    | ARABIC KASRA                                |
| ُ +و         | oo/ou  | ARABIC DAMMA followed by ARABIC LETTER WAW  |
| ِ +ى         | ee     | ARABIC KASRA followed by ARABIC LETTER YEH  |
| َ +ا         | aa     | ARABIC KASRA followed by ARABIC LETTER ALEF |

** additional diacritics not in the traditional system
for those we use diphthongs, i.e. compound vowels.
   | diacritic | examples                                      | note             |
   |-----------+-----------------------------------------------+------------------|
   | oa        | moat (death), soat (sound), noam (sleepiness) | "oo" but lighter |
   | ei        | leih (why), beit (home), la2eit (i found)     | "ee" but lighter |

* <<<shadda>>>
shadda in Arabic is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by.. yeah, you guessed it.. a repeated letter, e.g. yalla, ba7ebbek, kollo.

some people omit the second letter, causing one of the biggest sources of ambiguity in Franco text, as omitting the second letter normally yields a different word. try to convince your wife that the message "ha3dy 3alek bel mara" she found on your phone is supposed to be "ha3ddy 3alek bel marra" to know how important this is. we can't emphasize more that the second letter is not optional and text compliant to this guideline should always write repeated letters whenever there is a shadda.

** shadda with 8en
some people write 8en as 3', if you can't loose this habit, don't omit the shadda because it's ugly to write for example "sha3'3'al"; in this case you can write it as "sha3"al". so 3" = 3'3' = 3' + shadda. but for reasons like this we recommend against 3', use 8. 

the previous concept applies also if you are using 7' instead of 5 - for god knows why.

* <<<Digraphs>>> avoidance
Digraphs are two letters that behaves as a unit and is not the sum of its parts, e.g. "ch", "sh", "kh" and "th" in English.

Digraphs are ugly and makes words longer and harder to read, specially for repeating letters, i.e. shadda.
the only Digraph we use is "th". we are going with it now because it's rarely used in the Egyptian dialect and seems to be no sane alternative right now. this may be changed in further versions if some one contributed a good idea.
   
*** 5 instead of kh
5 is omnipresent in the Egyptian Franco, so that's a solved issue.

*** 4 instead of sh
depending on your age and where are you from, you might find 4 a bit strange, but it's already widely used in many Franco flavors.

earlier in the project's timeline, we thought about going with x to represent 4 as in Maltese - which is so close to be an Arabic dialect written with Latin letters - and many Latin languages, but the following summarizes why using 4 is a better idea:

- using x breaks the second boundary condition.
- it is easier to figure out its meaning if you didn't see it before, easier than x which requires unlearning first then learning.
- adheres more to the basic idea that distinguishes Franco from any other system, assigning sounds to numbers.
  
* The hyphen
the hyphen in Franco is used when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the "sh" and "th" sequence. for example:
- ana /s-hert/ embare7 l7ad elsa3a 3
- ana ennhrda s7et 3la /sot-ha/
 
hyphens can optionally be used after the definite article to ease readability.

* the definite article "el"
based on what dialect you are writing in, the definite article can be "el" or "al". write what you pronounce.

"el" ( or "al") in Franco is attached to the following word either directly or with a hyphen, e.g. /elwalad/ or /el-bent/.

some words starts with letters (sun letters) that assimilate the "l" in the definite article so that l is removed and shadda is added to the letter. for example some words like /elnahrda/ are often pronounced as /ennahrda/. both are valid ways to write the word. but note that if you are hyphening the word /ennahrda/, it's hyphened like /en-nahrda/.

to wrap up, you can write /elkonafa/ without hyphens either as /elkonafa/ or /ekkonafa/ or /ek-konafa/, /el-konafa/,

* prepositions
| traditional | Franco | attached | example       |           |
|-------------+--------+----------+---------------+-----------|
| في          | fe     | yes      | fekkonafa     | felkonafa |
| ب           | be     | yes      | berra7a       | belra7a   |
| على         | 3la    | depends  | sho5 3alwel3a |           |
| ف           | fa     | yes      | faro7t        |           |

prepositions like /be/ (“with”) or /fe/ (“in”) should be attached to the following definite article, thus becoming one entity bel or fel. and both should be attached the following word like bel-konafa

* Don't start with "2"
it's useless and ugly. 

| example     | should be  |
|-------------+------------|
| 2na         | ana        |
| 2amal maher | amal maher |
| 2egry       | egry       |
| 2e2lam      | e2lam      |
| 2oddam      | oddam      |

* TODO sample text
  here we should put a sample text that covers all possible cases.
