#+TITLE: Expect Franco
#+AUTHOR: saadnpq
#+DATE: 2019:5:20
#+OPTIONS: \n:t num:t toc:t
#+SETUPFILE: https://raw.githubusercontent.com/fniessen/org-html-themes/master/setup/theme-readtheorg.setup

* state of the project
the project is still in early development, but it's usable and reaching a more stable state with time, major changes happen less often and basic cases has been coverd.

* why?
- to have a standardized, written, documented and community developed Franco flavor.
- to have a consistent and searchable Arabic writing system.
- a reference for people with unreadable Franco
* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, however, it should not conflict with it (English alphabet).
3) as much as we can, there should be only one "right" way to write a word to achieve searchability.

* Character transliterations
  
| traditional | Franco | unicode name                   |
|-------------+--------+--------------------------------|
| ا           | a      | ARABIC LETTER ALEF             |
| آ           | aa     | ARABIC LETTER WITH MADDA ABOVE |
| ء           | 2      | ARABIC LETTER HAMZA            |
| ب           | b      | ARABIC LETTER BEH              |
| ت           | t      | ARABIC LETTER TEH              |
| ث           | th     | ARABIC LETTER THEH             |
| ج           | g,j    | ARABIC LETTER JEEM             |
| ح           | 7      | ARABIC LETTER HAH              |
| خ           | 5      | ARABIC LETTER KHAH             |
| د           | d      | ARABIC LETTER DAL              |
| ذ           | th     | ARABIC LETTER THAL             |
| ر           | r      | ARABIC LETTER REH              |
| ز           | z      | ARABIC LETTER ZAIN             |
| س           | s      | ARABIC LETTER SEEN             |
| ش           | 4      | ARABIC LETTER SHEEN            |
| ص           | S      | ARABIC LETTER SAD              |
| ض           | D      | ARABIC LETTER DAD              |
| ط           | T      | ARABIC LETTER TAH              |
| ظ           | Z      | ARABIC LETTER ZAH              |
| ع           | 3      | ARABIC LETTER AIN              |
| غ           | 8      | ARABIC LETTER GHAIN            |
| ف           | f      | ARABIC LETTER FEH              |
| ق           | Q      | ARABIC LETTER QAF              |
| ك           | k      | ARABIC LETTER KAF              |
| ل           | l      | ARABIC LETTER LAM              |
| م           | m      | ARABIC LETTER MEEM             |
| ن           | n      | ARABIC LETTER NOON             |
| ه           | h      | ARABIC LETTER HEH              |
| و           | w      | ARABIC LETTER WAW              |
| ى           | y      | ARABIC LETTER YEH              |

** Capital letters

the fact that Capital letters doesn't have any phonetic differences than lower case letters, makes it a perfect candidate to be included in Franco, as it is "backward compatible", by backward compatible we mean that if someone for example wrote ط as T instead of t, it won't effect the interpretation of the word if the receiver doesn't know this mapping. we basically loose nothing -[[*what we loose][ kinda]] - but we gain more clarification and disambiguation.

*** capital consonants 
we choose the following letters to have a Capital letter transliteration due its phonetic similarities with letters transliterated to the corresponding lower case letters.

| traditional | Franco | unicode name      |
| ض           | D      | ARABIC LETTER DAD |
| ط           | T      | ARABIC LETTER TAH |
| ظ           | Z      | ARABIC LETTER ZAH |
| ص           | S      | ARABIC LETTER SAD |

*** what we loose
- capitalization of names in Franco text, which is not used already.
- some minor confusion may arise in one case that requires three conditions to occur:
  1) a capitalized English word that starts with one of the few mapped capital letters in Franco
  2) that capitalized name exits alone without English context and surrounded by Franco text.
  3) that word can be interpreted as a Franco word
  but since this case is very unlikely to occur and relying on context is inevitable in mixed text anyway. it's not reasonable to throw all the benefits for such a rare case.

** Digraphs 
Digraphs are two letters that behaves as a unit and is not the sum of its parts, e.g. "ch", "sh", "kh" and "th" in English.

Digraphs are ugly and makes words longer and harder to read, specially for repeated letters, i.e. shadda.
the only Digraph we use is "th". we are going with it now because it's rarely used in the Egyptian dialect and seems to be no sane alternative right now (maybe $). this may be changed in further versions though.
   
| digraph | Franco |
|---------+--------|
| kh      |      5 |
| sh      |      4 |
| gh      |      8 |
| dh      |      D |

* diacritics and vowels
the table below shows the basic diacritics transliterations.

| traditional | Franco | Unicode name |
| َ            | a      | ARABIC FATHA |
| ُ            | o      | ARABIC DAMMA |
| ِ            | e      | ARABIC KASRA |

** long vowels
| traditional | Franco | Unicode name                      |
| ُ +و         | O      | ARABIC DAMMA + ARABIC LETTER WAW  |
| ِ +ى         | E      | ARABIC KASRA + ARABIC LETTER YEH  |
| َ +ا         | A      | ARABIC FATHA + ARABIC LETTER ALEF |

*** importance of long vowels (A,E,O)
without those we have no distinction between lots of words, for example:
- zaman and zamAn
- men and mEn
- 7aram and 7arAm
- malak, malAk, mAlak
  
*** why not oo,aa,ee ?
they appear so often in arabic - sometimes many times in one word - and they tend to make words a lot longer. they are used only in the beginning of words like aah, eed, oom.
 
** additional diacritics not in the traditional system
for those we use diphthongs, i.e. compound vowels.
   | diacritic | examples                 | note            |
   |-----------+--------------------------+-----------------|
   | ei        | leih (why), beit, la2eit | "E" but lighter |
   | oa        | moat (death), Soat, noam | "O" but lighter |

*** why we need new diacritics
the traditional system has no way to resolve the difference between for example:
- mOt and moat
- kOn and koan
- rO7 and roa7
- TEr and Teir

* shadda
shadda in Arabic is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by.. yeah, you guessed it.. a repeated letter, e.g. yalla, ba7ebbek, kollo.

some people omit the second letter, causing one of the biggest sources of ambiguity in Franco text, as omitting the second letter normally yields a different word. try to convince your wife that the message "ha3ady 3aleik bel mara" she found on your phone is supposed to be "ha3addy 3aleik bel marra" to know how important this is. we can't emphasize more that the second letter is not optional and text compliant to this guideline should always write repeated letters whenever there is a shadda.

** shadda with 8en
some people write 8en as 3', if you can't loose this habit, don't omit the shadda because it's ugly to write for example "sha3'3'Al"; in this case you can write it as "sha3"Al". so 3" = 3'3' = 3' + shadda. but this sounds over engineered, for reasons like this we recommend against 3', use 8. 

the previous concept applies also if you are using 7' instead of 5 - for god knows why.

* The hyphen
the hyphen in Franco is used when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the "sh" and "th" sequence. for example: 
- sme3t /sot-ha/
- byet-hayya2lak.
- btet-haz
 
hyphens can optionally be used after the definite article to ease readability, see [[*the definite article "el"][the definite article]].

* the definite article "el"
based on what dialect you are writing in, the definite article can be "el" or "al". just write what you pronounce.

"el" ( or "al") in Franco is never attached directly to the following word, it can be either written separately or attached with a hyphen, e.g. /el walad/ or /el-bent/. choose whatever you like, what matters is to be consistent.

some words start with letters (sun letters) that assimilate the "l" in the definite article so that l is removed and shadda is added to the letter. for example some words like /el naharda/ are often pronounced as /en-naharda/, whether or not this increases readability or not is very dependent on the context and the word itself, if you choose to assimilate the "l" in some word you should write it like /en-naharda/, not /en naharda/ or /ennaharda/.

* prepositions
  
| traditional | Franco | example             |
|-------------+--------+---------------------|
| ب           | b      | b we4 reglak        |
| و           | w      | a7la w a7la         |
| -ل          | l      | a4ky l mEn          |
| في          | f/fe   | kont f bAly         |
| على         | 3la    | 3la mAgy            |
| ف           | fa     | fa yakOn            |
| اللى        | elly   | elly hnAk da        |
| ما          | ma     | 3omrena ma hanerga3 |
| من          | men    | em4y men hena       |
| من ال       | mel    | mel ko4k            |
| من اللى     | melly  | melly hnAk da       |
| على ال      | 3al    | 3al mA4y            |
| إلي ال      | lel    | ray7a lel banAt     |
| في ال       | fel    | fel konAfa          |
| ب ال        | bel    | bel habal           |

prepositions inherit the same rules of attaching from the definite article, by that we mean that for example "fel konaafa" can be written as "fel-konaafa", and if you want to assimilate the l of the definite article in this word it should be written as "fek-konaafa".

ma can optionaly be attached directly to the following word. e.g. 3omry mansa.

** post-positions
  | traditional | Franco | example       |
  |-------------+--------+---------------|
  | دي          | de     | el bta3a de   |
  | ده          | da     | el bta3 da    |
  | دول         | doal   | el btoo3 doal |
  
* Don't start with "2"
it's useless and ugly.
# explain more as this is not obvious, so don't act like it is.

| example | should be |
|---------+-----------|
| 2na     | ana       |
| 2amar   | amar      |
| 2egry   | egry      |
| 2oddAm  | oddAm     |
| 2e2lAm  | e2lAm     |
| 2Ol     | ool       |

* general notes
** Arabic names
Arabic names should not be written in Franco, because simply no one has the right to decide how a name is pronounced other than the name holder himself.

** e in the end is y
  seeby not seebe
  
** the ghost vowel
this is an Egyptian dialect thing, we tend to not pronounce the second letter if it's a vowel.

- btA3 not betA3 
- ktEr not ketEr
- hnAk not henAk 
- m3Ak not ma3Ak 

but sometimes it's pronounced very clearly in certain words, we don't know if there is a well defined grammatical pattern that governs this phenomena, but we can say that if you don't know which way to go, remove the vowel.

* sample text
it's known that the beauty of a language comes from the beauty of text it has been written in.

"el banknote" by mostafa ibrahem, maybe it's dark a bit, but it's one of the best words ever written in the Egyptian language.

# is this a bit darker than appropriate here

hay7azzemOk.. zy el gneih fel astek..
haysebOlak el fotAt..
w ybe3Olak el amal fel e3lanAt..
w el hegra l blAd el plastic..
w f 5oTbet el gom3a 3n el ganna..
w oalet estanna, fAt el ktEr, hAnet 5alAs..
l7ad ma 5eil el 7kOma, ydOsoh 3agl el mecrobAs

el neZAm el 3Alamy bye2tel..
aw2At ktEr mn8eir roSAS

el hawa, hay7assal el mayya elly ba2et markAt.
ta3addodeyya ta3ny: ta3addod el 4arekAt..
7orreyya ta3ny: 7a2 fat7 el 2afaS..
3ala el nAs elly malha4 bAb

el a5TabOt el ra2smAly etsAb..
3ala el nAs elly malhA4 7aZ..
3ala el nAs elly malhA4 foraS

7ayAtak.. mohemma l bayya3En el 7elm..
wafAtak.. mohemma l bayya3En el oraS.
7esAbak 7atta fe abrak.. mohem..
ro5SeT el ganna mohemma l bayya3En el ro5aS..
w l bayya3En el dEn.. 
w l bayya3En el a5ra elly hatenSef el masakEn

"el 3Alam beyTTawwar".. yem4y esm masra7eyya..
amma el 7a2E2a el moD7eka el mobkeyya.. 
el 3aSAya elly betwa22af w betdawwar..
btem4y.. mn eed So7Ab el ganna.. 
l SbA3 So7Ab el bondo2eyya.. 
l gyOb So7Ab el bank

dam el 8alAba byt7ere2 fel tank
4Amem re7et-hom wenta betfawwel ?
el 8arb 7aymawwel e3mAr byAr el nafT..
l DamAn zeyAdet mansobAt el 4afT..
w DamAn baQA2ak 3abd motsawwel

ya zamEl el kawkab el mankOb..
rakb el 7aDAra mA4y bel ma2lOb 

ya zamEl el manTe2a el mankOba..
rakb el 7aDAra kan lazemlo rkOba

el 3Alem beyTTawwar.. 
wenta 4am3a btet7ere2 3ala4An..
borg el tegAra ynawwar

el 3aSAya heyya heyya w 4aklaha beyt7awwel..
el 3Alam beyt8awwel..
w enta wA2ef f we4 el TayyarAt bel TOb
hat3E4 7omAr w tmOt 7omAr.. 
a5rak t7es b entSAr..
lamma.. betwalla3 el a3lAm..
w tdOs 3ala SOret as7Ab el dolAr wel QarAr bel gazma
el Qanah fe na4ret el a5bAr..
hay2Olo 3annak enk fawDawy w QAtel..
nafs el Qanah wa2t el lozOm..
haTTalla3ak ma2tOl w betnADel
fe nAs ktEra akl 3e4ha el azma..
w dah .. 3Eboh..
en hAza el 3Alam Soatoh mn geiboh..
w mafE4 7a2E2a Sa3b tet2awwel
w fe nAs te3raf tbE3 el aah..
zay mabte3raf tbE3 el la2
el media bA2e3 7a2.. motagawwel

bo4ra l abnA2 el 3Alam tAlet mel 3Alam el awwal
bo4ra l abnA2 el 3Alam el hamagy mel 3Alam el ensAn.. 
el 3Alam el 7orr elly mabyedrab4 fel malyAn..
bs beygawwa3 blAd l7ad el moat..
el aatel el 4Ek el mo7taref..
abo Tal2 mn8eir Soat
fEh el gyO4 maba2O4.. labsEn hdOm mEry
wel TayyarAt maba2et4 betwazza3 man4orAt el ya2s
wel bonOk m4 7aysebOk tet7ebes.. bel3aks

en-naharda 7ATet e3lanAt 3al taks..
3ala4An 3aleih e2SAt..
bokra tet3alla2 3ala hdOmak zy ella3Eba fel mat4At

3Alam gedEd.. hat5o44o bemazAgak abl manzo22ak 
el kahana fEh.. labsEn bedal w karavattAt
hay2akklOk el 7a2E2a b ma3la2a f bo22ak 
w kasr 7o22ak yally m4 3Ayez..
3Alam demoQrAty ra2smAly sa3Ed
el 4erka fEh a2wa mn el awTAn

8aDbAn.. akEd 8aDbAn 
marbOt f sa2ya w btegry f makAnak
masgOn w m4 3Aref we4 sagganak
3Ayez t5abbat kobbayAt el 7abs 3al 2odbAn
lAkn hate3ml eih .. ma3zOr..
amrEka 3amalet segn mn8eir sOr..
amrEka rabTa el nAs f ba3DEhom.. 
amrEka rabTa el nAs w mrabbatAk bEhom

teddan f malTa ad ma7ateddan..
amrEka 7atefdal bet7eb el ba4ar geddan..
w bte3ml gmEl fEhom

fEha el 5eir ya haltara walla fEha flOs
amrEka fEha el 7elm.. w bladna fEha kabOs
el nAs t5Af.. amrEka t7mEhom
el nAs tgO3.. amrEka tddEhom
teksy bel eed el yemEn el lage2En 
ba3d ma edeiha el 4emAl t3arrehom
4erka bet-hed el blAd..
w 4erka tebnEhom 
4erka betbE3 el selA7..
w 4erka beTTabTab 3ala elly ymOt

el 3Alam byet2assem dewal 
el 3Alam byet2assem byOt 

el 3Alam byet2assem l bany-aadam..
w l banknote

maktOb 3ala 4hOd el blAd.. el mamso7En b astEka:
anta 7or.. ma lam taDor.. amrEka

* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# after-save-hook: org-html-export-to-html
# End:
