#+TITLE: Franco guideline draft
#+AUTHOR: saadnpq
#+DATE: 2019:5:20

* why?
- to have a standardized, written, documented and community developed Franco flavor.
- to have a consistent and searchable Arabic writing system.
- a reference for people with unreadable Franco
  
* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, however, it should not conflict with it (English alphabet).
3) as much as we can, there should be only one "right" way to write a word to achieve searchability.

* Character transliterations
  
| traditional | Franco | unicode name                   |
|-------------+--------+--------------------------------|
| ا           | a      | ARABIC LETTER ALEF             |
| آ           | aa     | ARABIC LETTER WITH MADDA ABOVE |
| ء           | 2      | ARABIC LETTER HAMZA            |
| ب           | b      | ARABIC LETTER BEH              |
| ت           | t      | ARABIC LETTER TEH              |
| ث           | th     | ARABIC LETTER THEH             |
| ج           | g,j    | ARABIC LETTER JEEM             |
| ح           | 7      | ARABIC LETTER HAH              |
| خ           | 5      | ARABIC LETTER KHAH             |
| د           | d      | ARABIC LETTER DAL              |
| ذ           | th     | ARABIC LETTER THAL             |
| ر           | r      | ARABIC LETTER REH              |
| ز           | z      | ARABIC LETTER ZAIN             |
| س           | s      | ARABIC LETTER SEEN             |
| ش           | 4      | ARABIC LETTER SHEEN            |
| ص           | S      | ARABIC LETTER SAD              |
| ض           | D      | ARABIC LETTER DAD              |
| ط           | T      | ARABIC LETTER TAH              |
| ظ           | Z      | ARABIC LETTER ZAH              |
| ع           | 3      | ARABIC LETTER AIN              |
| غ           | 8      | ARABIC LETTER GHAIN            |
| ف           | f      | ARABIC LETTER FEH              |
| ق           | q      | ARABIC LETTER QAF              |
| ك           | k      | ARABIC LETTER KAF              |
| ل           | l      | ARABIC LETTER LAM              |
| م           | m      | ARABIC LETTER MEEM             |
| ن           | n      | ARABIC LETTER NOON             |
| ه           | h      | ARABIC LETTER HEH              |
| و           | w      | ARABIC LETTER WAW              |
| ى           | y      | ARABIC LETTER YEH              |

* diacritics transliterations
| traditional | Franco | Unicode name                      |
| َ            | a      | ARABIC FATHA                      |
| ُ            | o      | ARABIC DAMMA                      |
| ِ            | e      | ARABIC KASRA                      |
| ُ +و         | O      | ARABIC DAMMA + ARABIC LETTER WAW  |
| ِ +ى         | E      | ARABIC KASRA + ARABIC LETTER YEH  |
| َ +ا         | A      | ARABIC FATHA + ARABIC LETTER ALEF |

** importance of long vowels (A,E,O)
without this we have not distinction between a lot of words, for example:
- zaman and zamAn
- men and mEn
- 7aram and 7arAm

** additional diacritics not in the traditional system
for those we use diphthongs, i.e. compound vowels.
   | diacritic | examples                            | note             |
   |-----------+-------------------------------------+------------------|
   | ei        | leih (why), eih, leil, beit, la2eit | "E" but lighter  |
   | oa        | moat (death), soat, noam            | "O" but lighter  |
   
*** TODO is A in rAye7 should be a new diacritic?
    the question is does this solves an ambiguity in text or is it just a matter of pronunciation ?
* <<<shadda>>>
shadda in Arabic is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by.. yeah, you guessed it.. a repeated letter, e.g. yalla, ba7ebbek, kollo.

some people omit the second letter, causing one of the biggest sources of ambiguity in Franco text, as omitting the second letter normally yields a different word. try to convince your wife that the message "ha3dy 3alek bel mara" she found on your phone is supposed to be "ha3ddy 3alek bel marra" to know how important this is. we can't emphasize more that the second letter is not optional and text compliant to this guideline should always write repeated letters whenever there is a shadda.

** shadda with 8en
some people write 8en as 3', if you can't loose this habit, don't omit the shadda because it's ugly to write for example "sha3'3'al"; in this case you can write it as "sha3"al". so 3" = 3'3' = 3' + shadda. but for reasons like this we recommend against 3', use 8. 

the previous concept applies also if you are using 7' instead of 5 - for god knows why.

* <<<Digraphs>>> avoidance
Digraphs are two letters that behaves as a unit and is not the sum of its parts, e.g. "ch", "sh", "kh" and "th" in English.

Digraphs are ugly and makes words longer and harder to read, specially for repeated letters, i.e. shadda.
the only Digraph we use is "th". we are going with it now because it's rarely used in the Egyptian dialect and seems to be no sane alternative right now (maybe $). this may be changed in further versions though.
   
*** 5 instead of kh
5 is omnipresent in the Egyptian Franco, so that's a solved issue.

*** 4 instead of sh
depending on your age and where are you from, you might find 4 a bit strange, but it's already widely used in many Franco flavors.

earlier in the project's timeline, we thought about going with x to represent 4 as in Maltese - which is so close to be an Arabic dialect written with Latin letters - and many Latin languages, but the following summarizes why using 4 is a better idea:

- using x breaks the second boundary condition.
- it is easier to figure out its meaning if you didn't see it before, easier than x which requires unlearning first then learning.
- adheres more to the basic idea that distinguishes Franco from any other system, assigning sounds to numbers.
  
*** TODO 8 instead of gh
* The hyphen
the hyphen in Franco is used when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the "sh" and "th" sequence. for example:
- ana /s-hert/ embare7 l7ad elsa3a 3
- ana ennhrda s7et 3la /sot-ha/
 
hyphens can optionally be used after the definite article to ease readability, see [[*the definite article "el"][the definite article]].

* the definite article "el"
based on what dialect you are writing in, the definite article can be "el" or "al". write what you pronounce.

"el" ( or "al") in Franco is never attached directly to the following word, it can be either written separately or attached with a hyphen, e.g. /el walad/ or /el-bent/. choose whatever you like, what matters is to be consistent.

some words starts with letters (sun letters) that assimilate the "l" in the definite article so that l is removed and shadda is added to the letter. for example some words like /el nahrda/ are often pronounced as /en-nahrda/, whether or not this increases readability or not is very dependent on the context and the word itself, if you choose to assimilate the "l" in some word you should write it like /en-nahrda/, not /en nahrda/ or /ennahrda/.

* Capital letters
there an Arabic transliteration scheme developed by Tim Buckwalter in the 1990s. it is an ASCII only but it is not practical as it represents Arabic orthoigraphy strictly one-to-one. it's not a writing system of its own, instead it's a mapping from Arabic letters and diacritics to ASCII letters. 

for instance this example is taken from [[https://en.wikipedia.org/wiki/Buckwalter_transliteration][this]] Wikipedia article. 
#+begin_quote
The First Article of The Universal Declaration of Human Rights:

Arabic Text\\
يُولَدُ جَمِيعُ ٱلنَّاسِ أَحْرَارًا مُتَسَاوِينَ فِي ٱلْكَرَامَةِ وَٱلْحُقُوقِ. وَقَدْ وُهِبُوا عَقْلًا وَضَمِيرًا وَعَلَيْهِمْ أَنْ يُعَامِلَ بَعْضُهُمْ بَعْضًا بِرُوحِ ٱلْإِخَاءِ.

Buckwalter Transliteration\\
yuwladu jamiyEu {ln~aAsi >aHoraArFA mutasaAwiyna fiy {lokaraAmapi wa{loHuquwqi. waqado wuhibuwA EaqolFA waDamiyrFA waEalayohimo >ano yuEaAmila baEoDuhumo baEoDFA biruwHi {lo<ixaA'i.

English Text\\
All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood
#+end_quote

if you noticed there is a smart idea Buckwalter introduced in this scheme, he assigned Arabic letters to Capital letters in English. the fact that Capital letters doesn't have any phonetic differences than the corresponding lower case letters, makes this a good candidate to be included in Franco as it is "backward compatible". by backward compatible we mean that if someone for example wrote ط as T instead of t, it will be interpreted correctly whether the receiver knows about this mapping or not. we basically loose nothing -[[*what we loose][ kinda]] - but we gain more clarification and disambiguation.

** mapped letters
we choose the following letters to have a Capital letter transliteration due its phonetic similarities with letters transliterated to the corresponding lower case letters.

| traditional | Franco | unicode name     |
| ض           | D      | ARABIC LETTER DAD |
| ط           | T      | ARABIC LETTER TAH |
| ظ           | Z      | ARABIC LETTER ZAH |

** what we loose
- capitalization of names in Franco text, which is not used already.
- some minor confusion may arise in one case that requires three conditions to occur:
  1) a capitalized English word that starts with one of the few mapped capital letters in Franco
  2) that capitalized name exits alone without English context and surrounded by Franco text.
  3) that word can be interpreted as a Franco word
  but this case is very unlikely to occur, so we can rely on context here, specially that relying on context is inevitable in mixed text anyway.

* prepositions

| traditional | Franco | example             |
|-------------+--------+---------------------|
| ب           | b      | b we4 reglak        |
| و           | w      | a7la w a7la         |
| إلي         | l      | a4ky l meen         |
| في          | f/fe   | kont f baly         |
| على         | 3la    | 3la regly           |
| ف           | fa     | nadany fa ro7t      |
| اللى        | elly   | elly hnak da        |
| ما          | ma     | 3omrena ma hanerga3 |
| من          | men    | em4y men hena       |
| من ال       | mel    | mel ko4k            |
| من اللى     | melly  | melly hnak da       |
| على ال      | 3al    | 3al ma4y            |
| إلي ال      | lel    | ray7a lel banaat    |
| في ال       | fel    | fel konaafa         |
| ب ال        | bel    | bel marra           |

prepositions inherit the same rules of attaching from the definite article, by that we mean that for example "fel konaafa" can be written as "fel-konaafa", and if you want to assimilate the l of the definite article in this word it should be written as "fek-konaafa".

** TODO me4 walla m4
** post-positions
  | traditional | Franco | example      |
  |-------------+--------+--------------|
  | دي          | de     | el bta3a de  |
  | ده          | da     | el bta3 da   |
  | دول         | doal   | el btoo3 doal |
  
* TODO Arabic names shouldn't be written in Franco
* TODO e in the end is y
  seeby not seebe
* TODO the second e (or vowel generally) in some words
this is probably an Egyptian dialect thing,
- beta3 or bta3 
- keteer or kteer
- henak or hnak
- m3aak or ma3aak

i am more toward being explicit, cause it sometimes may introduce ambiguity between words like nafsy and nefsy.
but it sometimes not there at all like in to2a3 w t2oom

* Don't start with "2"
it's useless and ugly. 

| example     | should be  |
|-------------+------------|
| 2na         | ana        |
| 2amal maher | amal maher |
| 2egry       | egry       |
| 2e2lam      | e2lam      |
| 2oddam      | oddam      |

* TODO sample text
  here we should put a sample text that covers all possible cases.
* you don't need mass adoption to benefit from this system
- searchable 
- use it in your files

* what do you think?
below are the points that maybe need more discussion: those are of course not the only points open for discussion, but stimulate your mind.
** 8 or 3'
this discussion probably will end up discussing the classic "backward compatibility vs good design" problem.
** Capital letters 
does we really want capitalization of names ?.
** any more sounds?
are there any additional sounds we didn't cover [[*additional diacritics not in the traditional system][here.]]
