#+TITLE: Franco guideline draft
#+AUTHOR: saadnpq
#+DATE: 2019:5:20

* Boundary conditions
1) Franco is a writing system for Arabic speakers, not a way to write Arabic to be pronounced by English speakers.
2) Franco constrains itself to ASCII characters not to English alphabet, though it should not conflict with English alphabet.
3) this guideline concern itself with readability and beauty as well.

* Character transliterations

| traditional | Franco | unicode name        |
|-------------+--------+---------------------|
| ا           | a      | ARABIC LETTER ALEF  |
| ء           | 2      | ARABIC LETTER HAMZA |
| ب           | b      | ARABIC LETTER BEH   |
| ت           | t      | ARABIC LETTER TEH   |
| ث           | th     | ARABIC LETTER THEH  |
| ج           | g      | ARABIC LETTER JEEM  |
| ح           | 7      | ARABIC LETTER HAH   |
| خ           | 5      | ARABIC LETTER KHAH  |
| د           | d      | ARABIC LETTER DAL   |
| ذ           | th     | ARABIC LETTER THAL  |
| ر           | r      | ARABIC LETTER REH   |
| ز           | z      | ARABIC LETTER ZAIN  |
| س           | s      | ARABIC LETTER SEEN  |
| ش           | 4      | ARABIC LETTER SHEEN |
| ص           | S      | ARABIC LETTER SAD   |
| ض           | d,D    | ARABIC LETTER DAD   |
| ط           | t,T    | ARABIC LETTER TAH   |
| ظ           | z,Z    | ARABIC LETTER ZAH   |
| ع           | 3      | ARABIC LETTER AIN   |
| غ           | 3'     | RABIC LETTER GHAIN  |
| ف           | f      | ARABIC LETTER FEH   |
| ق           | q      | ARABIC LETTER QAF   |
| ك           | k      | ARABIC LETTER KAF   |
| ل           | l      | ARABIC LETTER LAM   |
| م           | m      | ARABIC LETTER MEEM  |
| ن           | n      | ARABIC LETTER NOON  |
| ه           | h      | ARABIC LETTER WAW   |
| و           | w      | ARABIC LETTER HEH   |
| ى           | y,i    | ARABIC LETTER YEH   |

* diacritics transliterations
| traditional | Franco | unicode name |
| َ            | a      | ARABIC FATHA |
| ُ            | u/o    | ARABIC DAMMA |
| ِ            | i/e    | ARABIC KASRA |

* The hyphen
the hyphen in Franco is used when we want to emphasize that two characters should not be interpreted as a digraph. this occurs a lot in the sh and th sequence. for example:
- ana /s-hert/ embare7 l7ad elsa3a 3
- ana ennhrda s7et 3la /sot-ha/

hyphens can optionally be used after the definite article to ease readability specially for long words, .e.g. /el-kalam/, /bel-tayyara/.
* <<<shadda>>>
shadda in Arabic is a diacritic that is phonetically equivalent to a repeated letter. in Franco it is represented by.. yeah, you guessed it.. a repeated letters, e.g. yalla, ba7ebbek, kollo.

some people omit the second letter, causing one of the biggest sources of ambiguity in Franco text, as omitting the second letter normally yields a different word. we can't emphasize more that the second letter is not optional and text compliant to this guideline should always write words that pronounced with shadda with two letters.

* <<<Digraphs>>> avoidance
from Wikipedia Multigraphs are:
#+BEGIN_QUOTE
A multigraph (or pleongraph) is a sequence of letters that behaves as a unit and is not the sum of its parts, such as English ⟨ch⟩ or French ⟨eau⟩. The term is infrequently used, as the number of letters is usually specified:

Digraph (two letters, as ⟨ch⟩ or ⟨ea⟩)\\
Trigraph (three letters, as ⟨tch⟩ or ⟨eau⟩)\\
Tetragraph (four letters, as German ⟨tsch⟩) 
#+END_QUOTE
Digraphs are ugly and makes words longer and harder to read specially for repeating letters, i.e. shadda.
the only Digraph we use is th. we still can't find a sane alternative, but this may be changed in further versions if some one contributed a good idea.
*** 4=sh
why 4 to represent sh and not x for example like Maltese and many languages?

- 4 is already present in some new flavors of Franco.
- it is easier also to figure out its meaning if you didn't see it before. (easier than x which requires unlearning first then learning).
- adheres more to the basic idea that distinguishes Franco from any other system, assigning sound to numbers.
 
* the definite article "el"
based on what dialect you are writing in, the definite article can be "el" or "al". just write what you pronounce.

"el" ( or "al") in Franco is attached to the following word either directly or with a hyphen, e.g. /elwalad/ or /el-bent/.

some words starts with letters (sun letters) that assimilate the "l" in the definite article so that l is removed and shadda is added to the letter. for example some words like /elnahrda/ are often pronounced as /ennahrda/. both are valid ways to write the word. but note that if you are hyphening the word /ennahrda/, it's hyphened like /en-nahrda/.

to wrap up, you can write /elkonafa/ either as /elkonafa/, /el-konafa/, /ekkonafa/, or /ek-konafa/.

* prepositions
  
| traditional | Franco | attached | example       |           |
|-------------+--------+----------+---------------+-----------|
| في          | fe     | yes      | fekkonafa     | felkonafa |
| ب           | be     | yes      | berra7a       | belra7a   |
| على         | 3la    | depends  | sho5 3alwel3a |           |
| ف           | fa     | yes      | faro7t        |           |

prepositions like /be/ (“with”) and /fe/ (“in”) should be attached to the following definite article, thus becoming bel and fel. and both should be attached the following word like bel 

* Capital letters [experimental] 
there an Arabic transliteration scheme developed by Tim Buckwalter in the 1990s. it is an ASCII only but it is not practical as it represents Arabic orthoigraphy strictly one-to-one. it's not a writing system of its own, instead it's a mapping from Arabic letters and diacritics to ASCII letters. 

for instance this example is taken from [[https://en.wikipedia.org/wiki/Buckwalter_transliteration][this]] Wikipedia article. 
#+begin_quote
The First Article of The Universal Declaration of Human Rights:

Arabic Text\\
يُولَدُ جَمِيعُ ٱلنَّاسِ أَحْرَارًا مُتَسَاوِينَ فِي ٱلْكَرَامَةِ وَٱلْحُقُوقِ. وَقَدْ وُهِبُوا عَقْلًا وَضَمِيرًا وَعَلَيْهِمْ أَنْ يُعَامِلَ بَعْضُهُمْ بَعْضًا بِرُوحِ ٱلْإِخَاءِ.

Buckwalter Transliteration\\
yuwladu jamiyEu {ln~aAsi >aHoraArFA mutasaAwiyna fiy {lokaraAmapi wa{loHuquwqi. waqado wuhibuwA EaqolFA waDamiyrFA waEalayohimo >ano yuEaAmila baEoDuhumo baEoDFA biruwHi {lo<ixaA'i.

English Text\\
All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood
#+end_quote

if you noticed there is a smart idea Buckwalter introduced in this scheme, he assigned Arabic letters to Capital letters in English. the fact that Capital letters doesn't have any phonetic differences than the corresponding lower case letters, makes this a good candidate to be included in Franco as it is "backward compatible". by backward compatible we mean that if someone for example wrote ط as T instead of t, it will be interpreted correctly whether the receiver knows about this mapping or not. we basically loose nothing (kinda) but we gain more clarification and disambiguation.

** mapped letters
we choose the following letters to have a Capital letter transliteration due its phonetic similarities with letters transliterated to the corresponding lower case letters.

| traditional | Franco | unicode name     |
| ض           | D      | ARABIC LETTER DAD |
| ط           | T      | ARABIC LETTER TAH |
| ظ           | Z      | ARABIC LETTER ZAH |

** TODO what we loose
capitalization of names 

* Don't start with "2"
it's useless and ugly. 

| example     | should be  |
|-------------+------------|
| 2na         | ana        |
| 2amal maher | amal maher |
| 2egry       | egry       |
| 2e2lam      | e2lam      |
| 2oddam      | oddam      |

* TODO sample text
