#+title: Franco guideline draft
#+AUTHOR: saadnpq
#+date: 2019-05-18

a guideline, and hopefully a standard, for the Franco writing system. there is an associated blog post [[https://saadnpq.com/posts/franco/][here]] that describes the rationale behind this project and other things that are related but better to be separated from the guideline itself.

* state of the project
this is early 0.0001 pre alpha draft.
* TODO a fork for every dialect
this guideline is supposed to be general enough to fit all Arabic dialects, but it's written with Egyptian Arabic in mind and using Egyptian examples. cases that rarely appear in Egyptian Arabic may not be worked on, but i can imagine other dialects speakers forking it to fit theirs; that would be really awesome.
* FAQs
** what is the problem with the traditional system?
[[https://saadnpq.com/posts/franco/][thks]] blog post may answer this question and more.
** why this guideline written in English and not in Franco?
   this is an evolving guideline. if it is written in Franco, every update in the guideline means rewriting every thing to be compliant with itself.
** are you working on Franco to replace the traditional Arabic system?
Franco is just an alternative writing system that can coexist with any other writing system. we think Franco has more potential than Arabic in many situations like writing modern Arabic dialects and mixed English-Arabic text, but Franco is not yet capable of writing pure traditional Arabic text like Quran for example. when this guideline reaches a solid state we can test it against old Formal texts and see what are the limitations.

* how to contribute
help is very much appreciated and needed. the only requirement is to be an Arabic speaker, even if you don't use Franco we need to know what issues in the system holding you from adopting it. you can send me an email with your thoughts at [[mailto:saad@saadnpq.com][saad@saadnpq.com]] - or contact me by any way mentioned [[https://saadnpq.com/pages/reachme/][here]]. if you are familiar with git it's, of course, better to open an issue or a pull request in this repository. 

* contributors 
  when you submit a pull request please add your name here.
  
- [[saadnpq.com][saadnpq]]
